# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      home-assistant-test-stack:
        patterns:
          - "pytest-homeassistant-custom-component"
      dev-tooling:
        dependency-type: "development"
        exclude-patterns:
          - "pytest-homeassistant-custom-component"
        patterns:
          - "*"
